
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-program-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - pathType: ImplementationSpecific
            path: "/resources(/|$)(.*)"
            backend:
              service:
                name: resources-ms-service
                port:
                  number: 8080
          - pathType: ImplementationSpecific
            path: "/songs(/|$)(.*)"
            backend:
              service:
                name: songs-ms-service
                port:
                  number: 8081