apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: {{ .Values.namespace }}
  labels:
    current-date: {{ template "current-date" . }}
    version: {{ template "version" . }}
data:
  resources-db-name: resourcesdb
  songs-db-name: songsdb
  resources-db-init.sql: |
    CREATE TABLE IF NOT EXISTS resources (
        id SERIAL PRIMARY KEY,
        blob BYTEA
    );
  songs-db-init.sql: |
    CREATE TABLE IF NOT EXISTS songs (
        id SERIAL PRIMARY KEY,
        title VARCHAR(200),
        artist VARCHAR(150),
        album VARCHAR(150)
    );

