apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: eureka-server
  ports:
    - port: 8761
      targetPort: 8761

