---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: pgadmin
  ports:
    - port: 5050
      targetPort: 80