---
apiVersion: v1
kind: Service
metadata:
  name: resources-ms-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: resources-ms