
apiVersion: v1
kind: Service
metadata:
  name: songs-db-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: songs-db
  ports:
    - port: 5432
      targetPort: 5432