
---
apiVersion: v1
kind: Service
metadata:
  name: songs-ms-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: songs-ms