---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: eureka-server
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: maksimelyashevich/eureka-server-image:latest
          ports:
            - containerPort: 8761