
---
apiVersion: v1
kind: Service
metadata:
  name: resources-db-service
  namespace: k8s-program
spec:
  type: ClusterIP
  selector:
    app: resources-db
  ports:
    - port: 5433
      targetPort: 5432