
---
apiVersion: v1
kind: Service
metadata:
  name: songs-ms-service
  namespace: k8s-program
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: songs-ms