apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: songs-db-statefulset
  namespace: k8s-program
spec:
  serviceName: "songs-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: songs-db
  template:
    metadata:
      labels:
        app: songs-db
    spec:
      containers:
        - name: songs-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: songs-db-name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-email
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          startupProbe:
            exec:
              command:
                - psql
                - -U
                - postgres
                - -c
                - "SELECT 1;"
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: songs-db-storage
              mountPath: /var/lib/postgresql/data
            - name: db-init-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: db-init-volume
          configMap:
            name: postgres-configmap
            defaultMode: 484
            items:
              - key: "songs-db-init.sql"
                path: "init.sql"
  volumeClaimTemplates:
    - metadata:
        name: songs-db-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "hostpath"
        resources:
          requests:
            storage: 1Gi