---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: eureka-server
  replicas: {{ .Values.eurekaServer.replicaCount }}
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: {{ .Values.eurekaServer.image }}
          ports:
            - containerPort: 8761