
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-ms-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: songs-ms
  replicas: {{ .Values.songsMs.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: songs-ms
        owner: maksimelyashevich
    spec:
      containers:
        - name: songs-ms
          image: {{ .Values.songsMs.image }}
          ports:
            - containerPort: 8081
          env:
            - name: SONGS_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: songs-db-url
            - name: SONGS_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: songs-db-port
            - name: ENABLE_EUREKA_CLIENT
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: enable-eureka-client
            - name: EUREKA_URI
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: eureka-uri
          startupProbe:
            httpGet:
              path: /songs/health/startup
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /songs/health/readiness
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /songs/health/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 30
